### ISSUE TITLE
SADX Eggman Texlist Not Split

### ISSUE THREAD

**Issue by SkyNinja** [sonicretro/sa_tools#100]
So, I noticed Eggman's texture list isn't split still. I considered making a pull request, but the splitSADX.ini on github seems to be really out of date. So, anyway, here's the stuff:

```
[Dr. Eggman Textures]
type=texlist
address=50ECA4
filename=Objects/Common/Eggman Textures.ini
pointer=50ED58
```

**Comment by MainMemory** [comment]
The file in the release archive is pulled directly from GitHub.

**Comment by SkyNinja** [comment]
Ah, you right. Github's horrible search function, for god knows why, dumped me into a version of the file from two years ago.

**Comment by SkyNinja** [comment]
Created relevant pr: #101
