### ISSUE TITLE
SADXLVL2 Doesn't work!

### ISSUE THREAD

**Issue by BlackKnightGamer98** [sonicretro/sa_tools#12]
**Hello MainMemory**
I have a problem with SADXLVL2
The problem is that it asks me to select .ini file
(in SADXLVL2) i select "sadxlvl.ini" (which has came
in SADXLVL2'S Folder in "SATools.rar")
then it asks me to select a stage; I select emerald coast 1
then it gives me an error saying:
"Unhandled Expection MissingFieldExpection
Field not found:
SonicRetro.SAModel.SAEditor.Common.DataTypes.LevelData.geo".
I clicked on "Continue" and it kept Loading in emerald coast for 3 hours
then i ended process SADXLVL2.exe from task manager.
the next time i clicked report then reported this.
Please if you know how to fix this, then tell me

**Comment by MainMemory** [comment]
Honestly I can't figure out any situation that would result in an error like that. It works perfectly fine on my system, and the error implies that you somehow have an SAEditorCommon.dll file that's missing a field, which isn't possible because the whole build process would fail. Unless you have some kind of weird mismatched SA Tools install, or it's a bug in your .NET Framework installation.
Also, SA Tools comes in a 7z file, not a rar, and the sadxlvl.ini file is in the SADXPC folder, not the SADXLVL2 folder.

**Comment by ItsEasyActually** [comment]
Did you try loading any other levels and have the same results? Have you tried to update your tools to the latest version?

Those would be the first two things I would do in this situation.

**Comment by BlackKnightGamer98** [comment]
Yes i tried other levels and didn't work, but i guess there are missing
files in the .zip that you forgot to include in the .zip  because from what
i understood is that it needs files for each stage to edit, so if you can
add a .zip file with all stages data and others for every single stage, it
may work.

**Comment by ItsEasyActually** [comment]
Did you run the splitall.bat?

**Comment by BlackKnightGamer98** [comment]
Also i updated my tools.

**Comment by BlackKnightGamer98** [comment]
No, what does it do

**Comment by ItsEasyActually** [comment]
You have to run that to set everything up so you can use SADXLVL2.

**Comment by BlackKnightGamer98** [comment]
Okay whatever i'll try splitmarriedfiles.bat if your not gonna answer then
i'll tell you the result

**Comment by BlackKnightGamer98** [comment]
Oh, i thought these are data files, but i still want to know what does it
do?

**Comment by BlackKnightGamer98** [comment]
Sorry for messages sent not in time, my gmail is glitchy

**Comment by BlackKnightGamer98** [comment]
Thanks for your answer and as your name says, it's easy actually

**Comment by ItsEasyActually** [comment]
Did running split resolve your issues?

**Comment by BlackKnightGamer98** [comment]
After i runned split and went ECoast then i got the same error then i went
to mystic ruins cg daytime and evening and still the same error, so what
can i do?

**Comment by MainMemory** [comment]
There is something seriously wrong with your setup, and I have no idea what it is. You can try deleting SA Tools and downloading it again, or uninstalling and reinstalling the .NET Framework 3.5.

**Comment by ItsEasyActually** [comment]
On top of that redoing those two things, did you ensure all of the contents of the SADXPC folder was dropped into your install of SADX and that splitall.bat functioned as it was supposed to?

There's a quick start guide [here](https://dcmods.unreliable.network/sadxmodding/index.php/getting-started-with-sadx-modding/)

**Comment by MainMemory** [comment]
Well, there is one other thing. If you click on the "Report..." button in the error dialog, it will show more information that may be helpful.

**Comment by jcorvinus** [comment]
Can we close this because of how old it is? The current toolkit state probably doesn't even allow this problem to happen due to the re-structuring.

**Comment by BlackKnightGamer98** [comment]
Ok, Imma install this again and see, I didn't play SADX in so long.
