### ISSUE TITLE
can't import anything into salvl

### ISSUE THREAD

**Issue by umustbeloggedintododat** [sonicretro/sa_tools#123]
I'm trying to import levels from sa2b into salvl but it keeps on erroring me. wtf is even a key and address? do I need to go into someone's house?

I just get this error:
Unhandled ArgumentExpection

every. single. freaking. time.

oh yeah and here's my log file
[SALVL.log](https://github.com/sonicretro/sa_tools/files/5228048/SALVL.log)

**Comment by MainMemory** [comment]
Are you trying to open a level from the GC version? Because you really can't.

**Comment by umustbeloggedintododat** [comment]
yeah? how do I get dc level files? (I'm too poor to get pc version)

**Comment by MainMemory** [comment]
Well, once you have all the files extracted from the ISO, you can use the INI files with the manual split tool in the project manager to extract the data from each file, then look for the .sa2lvl files and either open them in SALVL or use the Blender addon.

**Comment by umustbeloggedintododat** [comment]
How do I extract the files? The DC "ISO" is a .CDI format

**Comment by umustbeloggedintododat** [comment]
help?

**Comment by MainMemory** [comment]
Google "extract cdi"?

**Comment by umustbeloggedintododat** [comment]
nvm I got it

**Comment by umustbeloggedintododat** [comment]
Keeps on telling me to configure a PC game even though this is Dreamcast.

**Comment by umustbeloggedintododat** [comment]
All I get is    not found. Aborting.

**Comment by PiKeyAr** [comment]
You can now open levels from the GC version in SADXLVL2 using the Advanced menu, but you still need the key and the address. For more information on binary files [see here](https://github.com/sonicretro/sa_tools/wiki/Working-with-Binary-Files).
