### ISSUE TITLE
SA2EventViewer: Instability and Color Issues

### ISSUE THREAD

**Issue by End-User-Person** [sonicretro/sa_tools#125]
At some point in the general updating process for the tools, some aspects of SA2EventViewer were adversely affected. Playback is generally much more unstable than it was previously, with the program locking up within a few seconds for several cutscenes. Additionally, the scene geometry for the GC/PC cutscene files is incorrectly colored to have a red hue. This only occurs with chunk models, as the scenes that use GC models for geometry render properly.

Edit: When the GC/PC events are split using SplitEvent, the red hue is visible on the affected models within the Scene 1 folder. Toggling the material colors setting does nothing to correct the issue.
![RedBG](https://user-images.githubusercontent.com/40090446/95671436-2587aa00-0b4c-11eb-80c0-ac20373cdda8.png)

**Comment by PiKeyAr** [comment]
I don't know about playback stability but the colors issue was fixed a while back.

**Comment by End-User-Person** [comment]
That only leaves the issue of why it seems to lock up more frequently than it did before. For now, I'll say it's a matter of my current setup not being strong enough to play back some of the more asset-intensive cutscenes.
