### ISSUE TITLE
PVMX support for PVMEditSharp

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#13]
Recently someone told me they still use PVMs for custom textures because PVMs are easier to work with, whereas PVMX doesn't have an easy to use editor. I think it would be nice to have a similar tool (or even support for PVMX format within PVMEditSharp) for PVMX archives.

**Comment by MainMemory** [comment]
First @SonicFreak94 needs to finish his new PVR library, so we aren't stuck dealing with Puyo Tools' limitations.

**Comment by MainMemory** [comment]
Solved with commit 6af26b1.
