### ISSUE TITLE
I can't get the texture editor to open.

### ISSUE THREAD

**Issue by StishStash** [sonicretro/sa_tools#131]
I click it, tired to open in as administrator, I even tried compatibility settings, It just won't open, doesn't even show up in task manager.

Can somebody please help?

**Comment by StishStash** [comment]
Actually, I can't get ANYTHING to open

**Comment by PiKeyAr** [comment]
See the system requirements listed here https://github.com/sonicretro/sa_tools/wiki/System-Requirements
