### ISSUE TITLE
Is there any way to use this on the Dreamcast DLC?

### ISSUE THREAD

**Issue by TeridaxXD001** [sonicretro/sa_tools#159]
Apparently [it's been done before](https://dcmods.unreliable.network/index.php/2020/10/10/dreamcast-dlc-mod-release/), but ProjectManager doesn't work on the files provided.

**Comment by PiKeyAr** [comment]
There's an SA1 DLC tool in the `bin` folder. If you just want to extract models from VMS files, run it like this: `DLCTool file.vms`.

**Comment by TeridaxXD001** [comment]
Can't see how I missed that. Thanks!
