### ISSUE TITLE
error with split.exe.

### ISSUE THREAD

**Issue by Darkorsomething** [sonicretro/sa_tools#16]
basically when i try to use splitSADX.exe, i get this error "the file sonic.exe is not valid for use with the INI splitSADX.ini"

**Comment by PiKeyAr** [comment]
Split only works with unmodified sonic.exe. If you're getting this error, it means your EXE is from an incompatible version or has been edited before (custom icon, old model/level mods etc.). Get a clean sonic.exe from the 2004 version.

**Comment by MainMemory** [comment]
We should probably just disable that method of version checking, none of the other files in SADX use it, and there are many reasons why someone might want to split a modified EXE. Something more like what the mod loader itself uses would be sufficient.

If you're certain you want to split the EXE you have, you can remove the MD5 line from splitSADX.ini.

**Comment by Darkorsomething** [comment]
I got a new sonic.exe file, works perfectly now. Thanks though
