### ISSUE TITLE
Trampol.cs is missing

### ISSUE THREAD

**Issue by GamecubeGuy** [sonicretro/sa_tools#162]
! upgraded object definitions for Windy Valley 3, and now Trampol.cs is missing. I downloaded the newest sa tools and it doesn't have it in their either. Also, I got this error when trying to report.
[image](https://user-images.githubusercontent.com/31381571/112524989-cecb0100-8d76-11eb-9f28-d407977ede14.png)

**Comment by PiKeyAr** [comment]
There is no Trampol.cs in SA Tools. It must've been a custom made object definition.
I'm not sure how to reproduce the error with the report button as it doesn't happen on my machine.

**Comment by GamecubeGuy** [comment]
I see, thank you for your help
