### ISSUE TITLE
Build Not Doing Anything

### ISSUE THREAD

**Issue by dqf318** [sonicretro/sa_tools#164]
While downloading new version of SATools, I've clicked on "buildSATools" a bunch of times, but it seemed like it did nothing at all.  I also did it with Visual Editor, but I get a few errors.

**Comment by PiKeyAr** [comment]
You need to build SA Tools in Visual Studio before you can run `buildSATools`.

If you aren't planning to edit the tools' source code, you can just get a pre-built package linked in this repo's readme.

**Comment by dqf318** [comment]
That's what I did.  And these are the errors I get:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file UI\ErrorDialog.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SAEditorCommon			
Error		Couldn't process file UI\EditorOptionsEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SAEditorCommon			
Error		Couldn't process file UI\SceneGraphControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SAEditorCommon			
Error		Couldn't process file UI\BinaryFileDialog.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SALVL			
Error		Couldn't process file UI\EditLevelInfoDialog.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SALVL			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SALVL			
Error		Couldn't process file ProjectManager.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	ProjectManager			
Error		Couldn't process file ProjectActions.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	ProjectManager			
Error		Couldn't process file NewProject.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	ProjectManager			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SA2CutsceneTextEditor			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SA2MessageFileEditor			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SA2StageSelEdit			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SADXFontEdit			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SADXTweaker2			
Error		Couldn't process file MusicListEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SADXTweaker2			
Error		Couldn't process file MessageFileEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SADXTweaker2			
Error		Couldn't process file NPCMessageEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SADXTweaker2			
Error		Couldn't process file SoundTestListEditor.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SADXTweaker2			
Error		Couldn't process file Form1.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SADXsndSharp			
Error		Couldn't process file UI\ModelCode.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SAMDL			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SAMDL			
Error		Couldn't process file UI\FindDialog.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SAMDL			
Error		Couldn't process file UI\ModelFileDialog.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SAMDL			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SASave			
Error		Couldn't process file MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	TextureEditor			
Warning		The referenced component 'SharpDX.Mathematics' could not be found.	SALVL			
Warning		The referenced component 'SharpDX.Direct3D9' could not be found.	SALVL			
Warning		The referenced component 'SharpDX' could not be found.	SALVL			
Warning		The referenced component 'Pfim' could not be found.	SA2StageSelEdit			
Warning		The referenced component 'Newtonsoft.Json' could not be found.	SAMDL			
Warning		The referenced component 'SharpDX.Direct3D9' could not be found.	SAMDL			
Warning		The referenced component 'SharpDX.Mathematics' could not be found.	SAMDL			
Warning		The referenced component 'SharpDX' could not be found.	SAMDL			
Warning		The referenced component 'Pfim' could not be found.	TextureEditor

**Comment by PiKeyAr** [comment]
I cloned the repo on a different computer and was able to build the solution without errors.

You need to unmark the .resx files as downloaded from the Internet. A quick search suggests this issue can occur if the repo is cloned on a remote drive or in a cloud-synced folder. Either way, this probably isn't an issue with the repo itself.

**Comment by dqf318** [comment]
Alright, looks like that worked.  But it still didn't seem like it did anything.  I don't see an exe for ProjectManager, for instance.

**Comment by PiKeyAr** [comment]
The compiled tools are placed in the `tools` folder. You can also create a package by running `buildSATools.exe` after building the solution.

**Comment by dqf318** [comment]
Ah, and they work!  Looks like that's over.
