### ISSUE TITLE
SA1 Dreamcast facial animations

### ISSUE THREAD

**Issue by TeridaxXD001** [sonicretro/sa_tools#165]
Are these rippable? The cutscene head models extract just fine from 1st_read.bin, but I can't find any associated animations.

**Comment by PiKeyAr** [comment]
They are rippable but they aren't included in the Dreamcast version's split data yet, so you'll have to find them yourself. SA1 talking heads should be compatible with SADX animations though, and there's a high possibility they're identical. The SADX animations are in the [new split](https://github.com/X-Hax/SADXModdingGuide/wiki/Finding-models#finding-models---new-split), which you can use to rip them from the PC version of the game.

**Comment by TeridaxXD001** [comment]
It doesn't work. SAMDL crashes when I specifically apply the PC facial animation to the Dreamcast cutscene head model.

**Comment by MainMemory** [comment]
Uh, yeah, they completely redid the faces for everyone between the Dreamcast and GameCube releases. There's no way it would work. Sorry, but until someone finds the data for it, you're out of luck.

**Comment by TeridaxXD001** [comment]
Of course not. The sad thing is that all I really want out of this endeavor is a pre-posed model of Sonic's head with a specific facial expression. I tried using Ninja Ripper on the PC version with the Dreamcast mod, but it rips everything in their default pose rather than what's actually on the screen.

**Comment by PiKeyAr** [comment]
I forgot that the Dreamcast Characters mod replaced facial motions so I assumed they were similar enough to just work. Anyway, they shouldn't be too hard to find, and I'll add them to SA1DC split that sometime soon.

**Comment by TeridaxXD001** [comment]
I actually figured out the Ninja Ripper thing (duh, shaders). But yes, that would be great, thanks.

**Comment by PiKeyAr** [comment]
The SA1 split now includes facial animations for Sonic, Tails, Knuckles, Amy, Big and Tikal. Their paths and filenames are the same as with their DX counterparts.
