### ISSUE TITLE
Suggestions to make the tools more user friendly

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#17]
In this issue I'd like to post a wishlist of sorts that I've had in mind during the last year working with the tools. Of course this is just my perspective after using the tools for my purposes, so you don't have to feel pressured to follow any recommendations listed here, but I just thought it would be a good idea to have some feedback documented from an ordinary modder's perspective. I'm going to be talking only about SA1/SADX tools as I've only worked with these two games.

### Part 1: Naming conventions and tools with similar functionality
I think the tools could benefit from having better names. It's a minor thing and I've contributed to the confusing names myself (ArchiveTool), but when I was getting started with SADX modding I found several tools very confusing:
~~1. StructConverter and DLLModGenerator are both used to export various game structs as data files+INI or C++ code. First, I think it would be easier if there was just one tool because they both do the same thing - the only difference is the location of source data, which ideally shouldn't be the end user's concern. If merging the tools isn't feasible, renaming them to StructConverterEXE and StructConverterDLL, or EXEStructExporter/DLLStructExporter or something like that would help. Either way DLLModGenerator could certainly use a better name because right now it sounds like it creates a DLL mod.
_Solution: Merge StructConverter and DLLModGenerator into one tool and/or rename them._~~ Basically resolved with the Data Extractor tool, which has a struct converter that doesn't rely on INI files.
2. Level viewers/editors: right now there's SADXLVL2 and SALVL, which have a lot of overlapping functionality. Ideally there should be just one level editor for both SA1 and SADX. SALVL feels like a stripped down version of SADXLVL2 anyway, and SADXLVL2 can already open SA1 levels if the INI data is tweaked a little. SADXLVL2 could benefit from being renamed to simple "Level Editor" if it opens levels from both games.
_Solution: Merge SALVL with SADXLVL2 and possibly rename SADXLVL2 something better._
~~3. Texture editors/PVM archivers: ArchiveTool, CompilePVM, PVMEditSharp, PVM2TexPack - all of these have overlapping functionality. While PAK-related tools could probably be left alone because it's a different format, PVM-related tools are kind of a mess right now. PVM2TexPack is a command line version of the "Export texture pack" option in PVMEditSharp, so it might as well be built into PVMEditSharp (if it isn't already). The command line tools would be unnecessary if PVMEditSharp had an easy way (such as arrow buttons like in the Mod Manager) to change texture order or edit the texture list directly. ArchiveTool wouldn't be needed if PVMEditSharp had an option to import/export PVR textures without format conversion. In addition, since PVMEditSharp crashes when trying to decode certain textures, a workaround to avoid that crash would be beneficial. If it can't decode a PVR texture, it could show an empty preview with a message saying the texture couldn't be decoded.
_Solution: 1) Add more command line options to PVMEditSharp and remove PVM2TexPack and CompilePVM; 2) Add a way to reorder textures in PVMEditSharp; 3) Add a way to import and export raw PVR textures in PVMEditSharp and remove ArchiveTool; 4) Add a workaround to avoid crashes with some PVR textures to improve versatility.~~ Sort of resolved, Texture Editor has had some UI improvements and doesn't crash on problematic textures anymore, and command-line tools for textures were merged into ArchiveTool.
~~4) The split tool(s). Basically the same kind of thing as with StructConverter/DLLModGenerator. Although the split tools are named better, it would be nice to have a unified split.exe for EXE/DLL/MDL/MTN and whatever else there is. It would also be nice if split (and other tools really) was separated from the game data, but I'll talk more about it in the next section.~~ Also sort of resolved. Data Extractor has its own split mode, and there is also a universal split tool that can extract anything supported by the tools from any file.

**Comment by PiKeyAr** [comment]
### Part 2: Documentation and tutorials
This should've been number 1 because it's way more important than tools' names. A major issue with the tools is lack of documentation, which makes the modders new to the scene give up early or go on x-hax and ask the same noob questions we've heard hundreds of times. Here are some of the most critical examples:
1) Level and model editors have pretty much non-existent documentation. They would massively benefit from having some kind of description their functionality, and they desperately need some kind of a built-in hint system. A full list of hotkeys would be a good start (I only found out you can preview animations in SAMDL almost after a year of using it), but a general hint system would be even better. Each button/command should have some tooltip explaining what it does, and pressing hotkeys should trigger visual feedback from the program - for example, when pressing CTRL or ALT or middle mouse button in SADXLVL2 it should show a message that the camera is now in "rotate" or "zoom" mode, or something like this.
_Solution: 1) Write documentation describing basic functionality of all tools (I can help with that); 2) Add a comprehensive hint system in all editors (tooltips are one way to do it); 3) Add a visual feedback feature to tell the user what the tool is doing - especially for things that involve hotkeys._
2) All command line tools should have a clear explanation of what they do and how they are supposed to be used when run without arguments.
_Solution: Add descriptions to all CLI programs detailing what they do and how they're used._
3) StructConverter is looking for a specific subset of INI files that are named whatever_data.ini, but it's never explained anywhere, so the user may select a non-data INI file and make the tool crash. In addition, the data exported by StructConverter and DLLModGenerator cannot be placed into the same folder as the split data, which is also not explained anywhere so I originally thought the tools weren't working when I was trying to export stuff for the first time.
Other than these bits, StructConverter and PMVEditSharp are intuitive enough, though the latter would benefit from some documentation describing its purpose and usage.
_Solution: 1) Add documentation for StructConverter/DLLModGenerator; 2) Possibly add a filename filter in the file open dialog to make the tools look specifically for "_data" files._

**Comment by MainMemory** [comment]
SALVL exists purely to edit SA1LVL/SA2LVL files, whereas SADXLVL2 requires setting up a project file. I'm not sure how feasible it is to make SADXLVL2 work in both modes.
I don't think we can do all the things we want to do with PVMEditSharp until we can fix or replace Puyo Tools. I could add PVR importing, but it would have to be decoded into a bitmap and reencoded into a PVR, which kind of defeats the point.
I don't know if it's a good idea to try to merge the "split" tools, as they all operate on entirely different types of data and in completely different ways. At best, we'd end up with one program that has four completely different modes of operation, and is that really any better?
Some of your issues would be solved by a unified project system with one tool to manage all the associated data files, but deciding how to implement such a system is difficult.
As for the data from DLLs, I don't know. We could definitely move things into different folders, but I'm not sure how we could give every file a unique name. It would require a fairly substantial rewrite of splitDLL, at least.

**Comment by PiKeyAr** [comment]
I'm happy that some of these suggestions are being considered. Here are a couple minor QoL/usability suggestions:
1) SAMDL (and all other tools maybe) should ask about saving changes only if changes have been made. Right now it asks "Do you want to save?" even if you just open a model file and close it without changes. This interferes with the workflow when you have to look through many models by opening and closing them one by one (this also sort of related to the "split data over the place/models not named" point mentioned previously).
2) SAMDL and SADXLVL2 could use some DPI scaling adjustments, the top toolbar in SADXLVL has pretty small icons at high DPI, and some interface elements (such as the bottom of the material editor) get cut off with 125% scaling.
3) Ideally SAMDL shouldn't crash when trying to open an incorrect address. Not a major issue, but a warning like "This doesn't appear to be a proper NJS_OBJECT, do you still want to open it?" would be better than just crashing. In most cases you can just click continue and try again, but after several failed attempts SAMDL may enter a state when it doesn't open models even if the address is correct until you restart the program.
4) There's an option to load animations in SAMDL, which is great, but it could benefit from a different implementation. Right now to load an animated object you need to specify the address of an NJS_OBJECT as model and NJS_ACTION as animation. However, since NJS_ACTION consists of a pointer to NJS_OBJECT and another pointer to NJS_MOTION, it's sort of redundant because the NJS_OBJECT is already known from the NJS_ACTION. In addition, some things in the game use NJS_MOTIONs directly without NJS_ACTIONs, which limits SAMDL's ability to open them. I think a more elaborate menu that specifies what exactly you're trying to open (NJS_OBJECT, NJS_MODEL_SADX, NJS_ACTION etc. + NJS_MOTION) would be beneficial.
5) Minor thing, but when selecting the SA1 format for binaries, it would be nice if the model type changed automatically to Basic because there are no Basic SADX models in SA1.

There are a few points I remember from working with the tools recently, hope some of this helps make them better.
