### ISSUE TITLE
Texture Editor: Add dimensions to exported texture packs

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#18]
At the moment texture packs exported by PVMEditSharp do not contain texture dimensions, so if anyone wants to add higher resolution textures they have to manually go through all textures and add their original dimensions to index.txt. Depending on the texture it may work without it, but a lot of GUI stuff breaks if dimensions for the original texture aren't specified.

Having PVMEditSharp add texture dimensions to index.txt will make it easier to work on custom textures for the game.

**Comment by PiKeyAr** [comment]
This issue came up again recently. Now that Texture Editor supports PVMX, being unable to set original texture dimensions makes creation of PVMX texture packs in it impractical. It also removes texture dimension from PVMX archives that had them when you export them again.

**Comment by MainMemory** [comment]
What, it does not remove dimensions from textures that have them.

**Comment by PiKeyAr** [comment]
If you open a PVMX that has texture dimensions specified in its index.txt and export it as a folder using the "Export all" option, it does. The dimensions are no longer listed in the newly created index.txt.

**Comment by MainMemory** [comment]
https://github.com/sonicretro/sa_tools/blob/master/TextureEditor/MainForm.cs#L636-L637

**Comment by PiKeyAr** [comment]
Yeah, that doesn't work. Try exporting the attached PVMX, and it produces index.txt without texture dimensions.
[TUTOMSG_SONIC_E_HD.zip](https://github.com/sonicretro/sa_tools/files/4222814/TUTOMSG_SONIC_E_HD.zip)
Here's the index.txt generated when it's extracted with SF94's PVMX tool:
`365400,padmanu.png,128x128
10000289,sprf_01_e.png,256x32
10000290,sprf_02_e.png,256x32
10000291,sprf_03_e.png,256x32
10000292,sprf_04_e.png,256x32
10000293,sprf_05_e.png,256x32
10000294,sprf_06_e.png,512x32
10000295,sprf_07_e.png,512x32
10000296,sprf_08_e.png,512x32
10000297,sprf_09_e.png,512x32
10000298,sprf_10_e.png,128x32
10000299,sprf_11_e.png,512x32
10000300,sprf_12_e.png,512x32
10000301,sprf_13_e.png,512x32
10000302,sprf_14_e.png,512x32
10000303,sprf_15_e.png,128x32
10000304,sprf_16_e.png,512x32
10000305,sprf_17_e.png,512x32
10000306,sprf_18_e.png,512x32
10000307,sprf_19_e.png,256x32
10000308,sprf_20_e.png,256x32
10000309,sprf_21_e.png,512x32
10000310,sprf_22_e.png,512x32
10000311,sprf_23_e.png,512x32
10000312,sprf_24_e.png,256x32
10000313,sprf_25_e.png,512x32
10000314,sprf_26_e.png,512x32
10000315,sprf_27_e.png,512x32
10000316,sprf_28_e.png,512x32
10000317,sprf_29_e.png,128x32
10000318,sprf_30_e.png,64x32
10000520,prf_null0.png,8x8
10000332,sprf_02b_e.png,512x32
`

**Comment by PiKeyAr** [comment]
Both issues should be fixed in [this commit](https://github.com/sonicretro/sa_tools/commit/322f4637162915a4427b2d50e01422e3922ea9c9) (hopefully).
