### ISSUE TITLE
SAMDL: UV options

### ISSUE THREAD

**Issue by xana43** [sonicretro/sa_tools#19]
I've been trying to get any model from SA2 for a while now, I've stayed up all night (occasionally falling asleep on my keyboard) trying to get a feasible model from SA2 (because SA1 just works) whenever I export models to .OBJ, or even .DAE the textures break, i'm not sure if that's something that can be fixed with a simple export option from SAMDL, but what happens is that, I put the OBJ into blender, then the texture on the model has the incorrect UV mapping attached to it, it would be nice to see if this can be fixed on export, because I have no idea how to UV map in blender (I only know that it tells the program where the texures go)

**Comment by ItsEasyActually** [comment]
The UV maps are ripped correctly. All you need to do is scale them by -1 usually on the Y axis. This could probably be fixed at some point, but the option to flipped UVs should be on the import options on Blender.

**Comment by jcorvinus** [comment]
Wasn't this fixed in commit: 2a0d422cc82ad55a531dd7c6f688d4f2dbf92dc0

Can this be closed?

**Comment by MainMemory** [comment]
Oh right, yes it was.
