### ISSUE TITLE
SA2 splitsonic2app error

### ISSUE THREAD

**Issue by xana43** [sonicretro/sa_tools#24]
when I first decompiled SA2 I had a feeling some files were missing, or were not properly being decompiled, so I look at everywhere, and then I compared the splitsonic2app.ini to what the batch file was spitting out, so I decided to pause the batch file when it got finished with it's operation, and then I got this error 

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at split.Program.Main(String[] args) in E:\AutoBuild\sa_tools\split\Program.cs:line 327

I'm not sure if it's a problem with the program, or i'm doing something wrong, I'd appreciate some information regarding this, thanks

**Comment by MainMemory** [comment]
The split program no longer exists, update your copy of SA Tools and use the project manager program.
