### ISSUE TITLE
Can't export model from SA2 event viewer

### ISSUE THREAD

**Issue by xana43** [sonicretro/sa_tools#33]
I might be doing something wrong here, but I'm trying to use the SA2 event viewer to try and get the biolizard model from this one event, the only problem is I can't seem to export the selected object as an obj, I've tried to do the same in SAMDL but I can't find the bilizard model anywhere there, but i've found it in the events, so either please tell me if i'm doing something wrong, or maybe try to see if there's a bug with the SA2 event viewer :)

**Comment by LBPPlayer7** [comment]
I can't do it either, and for extra specifics, the option to export is grayed out.

**Comment by MainMemory** [comment]
The export feature is currently disabled pending a total rewrite. You can try using splitEvent to extract the models, then open it in SAMDL and export from that, but I don't think that works right either. Hence why it's going to be rewritten.

**Comment by xana43** [comment]
when will the rewrite at least be started?

**Comment by MainMemory** [comment]
When someone finds the time to do it.

**Comment by illeatyourdonut** [comment]
Has anyone figure this out ? I just need king boom boo and boo model and mesh . Please help me

**Comment by xana43** [comment]
King boom boo’s model should be in the data files for the aquatic mine level, look up its location on the sonic hacking forums, if you can’t find it in the game’s files, then I’m going to give props to sega for successfully making sa2 a pain to extract data from

**Comment by illeatyourdonut** [comment]
I couldn’t find it and is the last mesh I need for my current level

**Comment by MainMemory** [comment]
You can now select a model in the scene and export it to a .sa2mdl file, which can be exported via SAMDL, so this is fixed, albeit not in the ideal way just yet.
