### ISSUE TITLE
Project Manager: Input data to Code Functionality

### ISSUE THREAD

**Issue by ItsEasyActually** [sonicretro/sa_tools#36]
A quick feature I think may prove extremely useful would be to add in some functionality where we can just input a file (or files) and have them auto-converted to a C++ file. 

Currently, this process requires editing the data and going through the process with the build functions. This can cause issues if you're replacing entire files of data with new filenames or adding in new files as a whole as the hashes will no longer be relevant and would be useless in several instances. 

Adding functionality along these lines can work similar to the Manual Split Tools as far as I'm concerned. It will speed up the export process a lot when it comes to only needing to export code for a handful of files. The only main issue I could see is with the data type needing to be defined somehow, but I would imagine there's some way to do that with relative ease.

**Comment by PiKeyAr** [comment]
The newly added Struct Exporter tool provides a quick way to convert levels, models and animations. Having this in one of the GUI tools such as the Project Manager or a completely new tool would be still nice, though.

**Comment by ItsEasyActually** [comment]
I agree this one's _basically_ been handled. I'm leaving it open until the pull request with the overhaul to the Project Manager is complete since this entails a Project Manager functionality that still isn't implemented currently.

**Comment by PiKeyAr** [comment]
I think this basically resolves it?
![image](https://user-images.githubusercontent.com/23312549/107842883-ee7f1900-6e09-11eb-9b71-7c0ec79c403f.png)

**Comment by ItsEasyActually** [comment]
Datatoolbox covers this issue and the soon to be added ToolsHub expands on the idea in its file viewer. This issue has been effectively resolved for a while, so I'm going to go ahead and close this.
