### ISSUE TITLE
SALVL: Unable to move or rotate level pieces

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#38]
In SALVL, the arrows used to move level items don't seem to be usable. They also aren't colored.
![image](https://user-images.githubusercontent.com/23312549/53677202-aaafa980-3cef-11e9-92aa-5612d0c8ee12.png)
Same for the "rings" used to rotate level pieces in Rotate Mode. In addition, those rings may show up far away from the item you've clicked on, making it difficult to find (example: try clicking around Egg Carrier Outside 2).

**Comment by PiKeyAr** [comment]
Still an issue with the current version.

**Comment by PiKeyAr** [comment]
Still happening with the latest update.

**Comment by jcorvinus** [comment]
Should be fixed here: https://github.com/sonicretro/sa_tools/commit/83792e84043d2894666aa7d8ab5c77efe0209c6e
Please test and respond with results

**Comment by PiKeyAr** [comment]
Nope, same issue and sometimes the arrows show up for a fraction of a second and disappear completely. Also the ability to select things is affected by resizing or maximizing the window - e.g. it's difficult to select things after the window size is changed from maximum.
![image](https://user-images.githubusercontent.com/23312549/73497881-241fb280-43ff-11ea-927e-2e2104f7f172.png)

**Comment by PiKeyAr** [comment]
I tested it a bit more and found the following:
1) The arrows are black in SALVL but they do work if the window size isn't changed. 
2) Selection stops working properly if the window size changes, but it works again if the window is resized back to the previous size.
3) The arrows are properly colored in SADXLVL2, but like in SALVL they are affected by 2.

**Comment by PiKeyAr** [comment]
The color issue was fixed in [this commit](d37df578f7c976f304bf6b4d363b27fe35d27116), the other issue was moved to #89.
