### ISSUE TITLE
SADXLVL2: Compile errors/crash when loading Windy Valley 3

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#39]
Steps to reproduce:
1. Create a new project.
2. Run SADXLVL2.
3. Select Windy Valley 3.
You get this dialog:
![image](https://user-images.githubusercontent.com/23312549/53677215-e9ddfa80-3cef-11e9-8c2f-9abab238b7b0.png)
If you click no, the level loads. If you click yes, you get this error:
![image](https://user-images.githubusercontent.com/23312549/53677225-037f4200-3cf0-11e9-880c-267dffa3698c.png)
Note: Selecting "Yes" also appears to delete some object definitions, which causes other levels to crash too, so you have to recreate the project.

Log details:
> System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\sat\SADXPC\SADXPC\objdefs'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
>    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
>    at System.IO.Directory.GetFiles(String path)
>    at SonicRetro.SAModel.SADXLVL2.MainForm.CopyFolder(String sourceFolder, String destinationFolder) in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 550
>    at SonicRetro.SAModel.SADXLVL2.MainForm.CopyDefaultObjectDefintions() in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 602
>    at SonicRetro.SAModel.SADXLVL2.MainForm.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 869

**Comment by jcorvinus** [comment]
Looks like this is being caused by the auto-updater failing to find the right directory for object definitions to pull from when updating. The path seems to be relative to sa tools and not sadxlvl2, which is causing it to be wrong. To recover from this, manually copy the objdefs from SA Tools\SADXPC\objdefs to your project's objdefs folder

**Comment by PiKeyAr** [comment]
Looks like this is no longer an issue with the latest version.
