### ISSUE TITLE
SAMDL stopped showing animation ID in window title

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#40]
Unless it's hidden elsewhere, it's currently impossible to tell which animation is being played in SAMDL. The previous versions of SAMDL displayed the animation ID in the window title, which was useful in identifying character animations. It also displayed some other useful information, like the frame number and camera rotation.
![image](https://user-images.githubusercontent.com/23312549/57005256-6ec29300-6c11-11e9-8ec1-04487a9c6b18.png)
The latest version of SAMDL would benefit from having this information displayed somewhere.

**Comment by MainMemory** [comment]
It should probably be displayed in a status bar, like SA2 Event Viewer does.

**Comment by PiKeyAr** [comment]
I like that it's now implemented in the status bar. Looks good, great job!
