### ISSUE TITLE
SADXLVL2: DeathZone doesn't work

### ISSUE THREAD

**Issue by Sora-yx** [sonicretro/sa_tools#41]
Hello,
I'm using SADXLVL2 to edit some specific stages, but I noticed a thing, if you edit a level then save it, death zones will no longer work in-game. (Not all of them, just the ones in the stage you edited.)
I didn't edit any death zone myself, I also checked if they were on "true" on SADXLVL2, the  ini file looks correct as well. 

I updated my SAtools with the last version, I even made a test with a new project, I tried to edit Windy Valley act 3 by adding a ring  and well... still the same issue. It disabled the death zone.
So I don't know... is this knew? But it's really annoying, since you can easily finish a stage because of that. 

![1](https://user-images.githubusercontent.com/50106301/57023427-4c8d3d00-6c32-11e9-873c-3b0cdfc8f68c.PNG)
![2](https://user-images.githubusercontent.com/50106301/57023428-4c8d3d00-6c32-11e9-8980-44b797016a55.PNG)

**Comment by PiKeyAr** [comment]
Possibly related #37

**Comment by MainMemory** [comment]
Are you exporting the mod as INI? The mod loader is known to have a problem loading death zones from INI.

**Comment by Sora-yx** [comment]
I believe so? I'm using the Project Manager from SA Tools and the "auto build" option. 
My mod.ini uses sonic_data.ini and all the stuff like that.

Is there a way to changes that so I could have functional death zone? Because I don't really know how to import custom level without ini file.

**Comment by MainMemory** [comment]
You could do a manual build and export to C++, or edit the ini to exclude the death zones if you haven't edited them, but really, this is a bug on the mod loader, not SA Tools.

**Comment by MainMemory** [comment]
As it turns out, there was a slight issue with the exporter that stripped file extensions from the outputted files, which I fixed in 2e069eb. sadx-mod-loader/d753885 fixes the issue on the mod loader's end.
