### ISSUE TITLE
Manual Split: Close on "Do Split"

### ISSUE THREAD

**Issue by InTheBeef** [sonicretro/sa_tools#44]
When attempting to split any file using any configuration the GUI closes, an empty folder is created and the GUI returns to the menu (Project Manager). No errors are given so I can't really go any further. This does not seem to be related to the version of the game I use.

**Comment by jcorvinus** [comment]
Please describe all of the data you're feeding to Split - what is the full path to the file? What is the full path to the data mapping? What are the file contents, which split mode are you using (Bin, DLL, model)? What is the full path of the output directory? What game are you using?

**Comment by InTheBeef** [comment]
Full path to Manager - "X:\Program Files\SA Tools\ProjectManager"
Full path to GC file/s - "X:\Program Files\Emulators\SonicDump\root\???.prs" (This occurs with both .pak and .prs, prs being what I would like to access.)
Not sure what "data mapping" refers to, apologies.
File contents are models / textures afaik. Like I said though, seems like any file causes it to close.
Split mode Model. 
Output directory: "X:\New folder\New folder\SonicDumpFiles" (New Folder is a Windows error, in reality it's BEEF\Desktop\, this has never caused a problem before so I doubt it's related, but I will test a different location.)
This occurs with both the PC and Gamecube version regardless of if I enable big endian.

**Comment by MainMemory** [comment]
There aren't any model files named "root". You're looking for filenames ending with "MDL.PRS", such as "SONICMDL.PRS". That is, assuming you're specifically looking for the character models.

**Comment by InTheBeef** [comment]
Sorry, that was a typo. root is the name of the folder, "root\???.prs" is what I meant. I didn't know the filename ending with MDL was required, didn't seem to be noted anywhere. Thanks.

**Comment by InTheBeef** [comment]
Seemed to resolve itself after a restart. Suggest tutorial is updated to clarify the **mdl**.prs is required.
