### ISSUE TITLE
SAMDL: Broken SA2B Model Export

### ISSUE THREAD

**Issue by InTheBeef** [sonicretro/sa_tools#45]
When exporting a model that displays perfectly within SAMDL's view as Collada format, the file only imports as bounding boxes/axis with no geometry, in 3DS Max, Blender, and Noesis.
When exporting as OBJ/Multi-OBJ it displays an Error: Inspect the Output File for more details, 3DS Max displays "Invalid vertex index" on import. Textures appear to export without problem.

**Comment by MainMemory** [comment]
This will be fixed by @Exant64's pending Assimp implementation.

**Comment by CrashOveride95** [comment]
Offtopic but is it planned for assimp to work on both SA1 and SA2 or just SA2

**Comment by MainMemory** [comment]
Yes

**Comment by MainMemory** [comment]
Fixed with new export system.
