### ISSUE TITLE
SAMDL: Add more toggles for evalflags

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#47]
Would be nice to have eval flags such as NJD_EVAL_HIDE and NJD_EVAL_BREAK toggleable here 
![image](https://user-images.githubusercontent.com/23312549/59207979-1ce33480-8be3-11e9-8550-738d24bf60ae.png)

**Comment by MainMemory** [comment]
Those flags are managed automatically by the library.
