### ISSUE TITLE
sadxlvl2: export seems to be not working

### ISSUE THREAD

**Issue by igdegoo** [sonicretro/sa_tools#51]
1. When i go to the export tab > obj in sadxlvl2 the everything option is grayed out
2. when i choose to export level geo instead i get a tiny obj file (less than 32 bytes) that obviously has no geometry

using latest sa tools

**Comment by MainMemory** [comment]
We're in the middle of replacing the entire export system. These things will all be fixed eventually.

**Comment by igdegoo** [comment]
ok is there an older version that works? because sonic adventure stages are on the models resource

**Comment by CrashOveride95** [comment]
SA tools builds unfortunately are not archived to my memory

**Comment by Shadowth117** [comment]
I believe if you select every geo piece you can do an export of the level geometry. However I realize this is far from ideal. SAlvl may also have a more functional export at the moment.

**Comment by PiKeyAr** [comment]
I don't know whether OBJ export works in this version, but here's a July 2018 build of SA Tools right before the Project Manager update. http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/SA%20Tools_jul2018.7z

**Comment by PiKeyAr** [comment]
OBJ export for level geometry and selected level items should work now in the current version of SADXLVL2. You can export the whole level but SET objects can't be exported at the moment. The "Everything" option has been removed as it was never implemented and I'm not sure if anyone is planning to make SET items exportable as models.
