### ISSUE TITLE
SADXLVL2: Position arrows show up at the model's object coordinates rather than geometry location

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#55]
![image](https://user-images.githubusercontent.com/23312549/65408280-c90dfb80-de1f-11e9-8815-c9c43e937146.png)
This becomes an issue in larger levels with large meshes that have the 0 0 0 coordinate (or similar), so you have to either input coordinates manually or go back to the level's starting point to reposition the model.

**Comment by PiKeyAr** [comment]
Better example:
![image](https://user-images.githubusercontent.com/23312549/65408443-3752be00-de20-11e9-8951-652e34b9b2c4.png)

**Comment by PiKeyAr** [comment]
Is it really fixed? Using the latest version from today's update
![image](https://user-images.githubusercontent.com/23312549/72695600-73065600-3b7c-11ea-9581-97bd64287219.png)

**Comment by jcorvinus** [comment]
You are using 'origin.' Set the pivot mode to 'center of mass'

**Comment by PiKeyAr** [comment]
That worked. Thank you!
