### ISSUE TITLE
SA tools won't let me "Delete All SET Items of Type"

### ISSUE THREAD

**Issue by BCMediaPlayer** [sonicretro/sa_tools#59]
When I try to delete checkpoints, item boxes, or rings, with the Delete All of Type function, I get this notification, and it doesn't work. Can this be fixed?
![bandicam 2019-11-04 15-31-10-407](https://user-images.githubusercontent.com/57376112/68166796-5319ab80-ff18-11e9-9a73-10cb5b71194b.png)

**Comment by MainMemory** [comment]
Fixed in 792e6e4.
