### ISSUE TITLE
Chunk model "Use Texture" always saved active

### ISSUE THREAD

**Issue by Shadowth117** [sonicretro/sa_tools#68]
While this flag can be disabled in SA Tools, it will not save and ingame and on reload of the file this will be clear.
Tested on this model for reference
[ewalktex.zip](https://github.com/sonicretro/sa_tools/files/3827865/ewalktex.zip)

[268.zip](https://github.com/sonicretro/sa_tools/files/3827864/268.zip)

**Comment by MainMemory** [comment]
Chunk models don't have a "Use Texture" flag. Textures can only be disabled by removing UVs from the poly data.
