### ISSUE TITLE
SA2 PC: ReplaceFile function doesn't work with .pak texture files

### ISSUE THREAD

**Issue by End-User-Person** [sonicretro/sa_tools#71]
Attempting to replace a .pak texture file using the ReplaceFile function via code results in one of two outcomes: Either the game crashes upon attempting to load the affected textures, or the .pak replacement is ignored entirely.

Whenever a .pak file already exists somewhere, either in the game itself or via enabled mods, setting a function to replace the file and its .prs equivalent is necessary for any changes to take effect, though the game will only recognize the .prs texture file. Having the replacement .pak texture file in its appropriate location will crash the game with this message:
```
Microsoft Visual C++ Runtime Library

Runtime Error!

Program: [path to sonic2app.exe]

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

Replacing event cutscene textures produces the second outcome, though the process of setting the function to replace the .pak and .prs versions of the files is still required, even if there is no .pak file in the game's directory or other mods.

**Comment by MainMemory** [comment]
Wrong repo.
