### ISSUE TITLE
SAMDL: Export options

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#8]
1. ~~Exporting animations as code
At the moment this can be done via StructConverter, but exporting the loaded animation together with the model's code would be great.~~ Fixed.
2. ~~"Export with textures" checkbox
When a PVM is loaded, exporting a model as code adds an enum with texture names and uses texture names instead of texture ID numbers. Being able to export models with texture indices without restarting SAMDL would be great.~~ Fixed
3. ~~Exporting OBJ without textures leads to a crash~~ (fixed), also even with textures I'm not sure if it exports correctly, at least in Misfit Model 3D all materials appear empty and you have to set textures manually.

**Comment by MainMemory** [comment]
I believe the third point has been made irrelevant with the new exporter.

**Comment by PiKeyAr** [comment]
1 and 2 have been implemented, 3 is fixed partially. OBJ export (what's left of it) still seems kinda wonky but it's less critical now that there are other export options and the Blender addon.
