### ISSUE TITLE
"ProjectManager" "GameConfig" Not Seeing Game Installs

### ISSUE THREAD

**Issue by gudenau** [sonicretro/sa_tools#94]
I have extracted "SA Tools.7z" next to "sonic2app.exe" and launched "SA Tools\ProjectManager\ProjectManager.exe" and entered the paths to SA2 and SADX via the text box and the browse button but neither seem to be recognized.

![image](https://user-images.githubusercontent.com/5642329/78512163-f3922700-7767-11ea-95ef-945cc3b19daa.png)

![image](https://user-images.githubusercontent.com/5642329/78512166-f856db00-7767-11ea-9e5e-ff63451a324a.png)

![image](https://user-images.githubusercontent.com/5642329/78512169-fbea6200-7767-11ea-825f-7fe759bee4e5.png)

![image](https://user-images.githubusercontent.com/5642329/78512172-00167f80-7768-11ea-84be-b598e61541e4.png)

[I am attempting to follow the ripping guide.](https://github.com/sonicretro/sa_tools/wiki/Data-Ripping)

**Comment by jcorvinus** [comment]
SA Tools doesn't need to go next to the sonic2app.exe file, an in fact I recommend keeping SA tools separate from the games in your file system. That said, I don't think that's the cause of the issue. Can you post the full text strings that are in the 'sadx pc location' and 'sa2 pc location' fields? My guess is that the paths supplied might not be precise enough and be off by what the program is expecting by a level or two.

**Comment by gudenau** [comment]
`D:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure DX`
`D:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2`
And the `SA Tools` directory is next to `sonic2app.exe`, not the contents of.

**Comment by MainMemory** [comment]
Do you have a file named sonic.exe in the Sonic Adventure DX folder, and a file named SA2ModManager.exe in the Sonic Adventure 2 folder?

**Comment by gudenau** [comment]
I don't have sonic.exe, there is a `Sonic Adventure DX.exe` though. Grabbing the SA2ModManager executable seems to have worked for SA2B though.

**Comment by MainMemory** [comment]
You're going to need this: https://www.moddb.com/mods/sadx-dreamcast-conversion/news/new-mod-installer-now-available1

**Comment by gudenau** [comment]
Might want to make a note of these things on https://github.com/sonicretro/sa_tools/wiki/Data-Ripping
