### ISSUE TITLE
Issue with Texture Editor?

### ISSUE THREAD

**Issue by angelicferal** [sonicretro/sa_tools#99]
![image](https://user-images.githubusercontent.com/63668032/79258954-cbc65180-7e40-11ea-9852-aa338dc166ca.png)
This shows up whenever I try to open a PVM or PVMX file? I repaired my vcredistribute and my DirectX is DirectX 12, so I don't know what's wrong.

**Comment by MainMemory** [comment]
You need to install the DirectX end-user runtimes.
